VLLM_PROMPT_BS_BUCKET_MIN=1 \
VLLM_PROMPT_BS_BUCKET_STEP=1 \
VLLM_PROMPT_BS_BUCKET_MAX=1 \
VLLM_DECODE_BS_BUCKET_MIN=1 \
VLLM_DECODE_BS_BUCKET_STEP=1 \
VLLM_DECODE_BS_BUCKET_MAX=1 \
VLLM_PROMPT_SEQ_BUCKET_MIN=256 \
VLLM_PROMPT_SEQ_BUCKET_STEP=256 \
VLLM_PROMPT_SEQ_BUCKET_MAX=1024 \
VLLM_DECODE_BLOCK_BUCKET_MIN=256 \
VLLM_DECODE_BLOCK_BUCKET_STEP=256 \
VLLM_DECODE_BLOCK_BUCKET_MAX=1024 \
RUNTIME_SCALE_PATCHING=1 \
PT_HPU_WEIGHT_SHARING=0 \
VLLM_EXPONENTIAL_BUCKETING=false \
QUANT_CONFIG=/software/data/vllm-benchmarks/inc/qwen3-30b-a3b/maxabs_quant_g3.json \
VLLM_SKIP_WARMUP=true PT_HPU_LAZY_MODE=0 ./run_qwen_3_30b_fp8_profiling_noinstruct.py --chat-template llama-3.jinja
